// Generated by https://quicktype.io

export interface ProjectsResponse {
    data: Project[];
    meta: Meta;
}

export interface Project {
    id:         number;
    attributes: ProjectAttributes;
}

export interface ProjectAttributes {
    title:       string;
    createdAt:   string;
    updatedAt:   string;
    publishedAt: string;
    description: string;
    slug:        string;
    repository:  string;
    information: string;
    category:    Category;
    stack:       Stack[];
    image:       Image;
}

export interface Category {
    data: CategoryData;
}

export interface CategoryData {
    id:         number;
    attributes: CategoryAttributes;
}

export interface CategoryAttributes {
    name:        string;
    createdAt:   string;
    updatedAt:   string;
    publishedAt: string;
}

export interface Image {
    data: ImageData;
}

export interface ImageData {
    id:         number;
    attributes: FluffyAttributes;
}

export interface FluffyAttributes {
    name:              string;
    alternativeText:   string;
    caption:           null;
    width:             number;
    height:            number;
    formats:           Formats;
    hash:              string;
    ext:               string;
    mime:              string;
    size:              number;
    url:               string;
    previewUrl:        null;
    provider:          string;
    provider_metadata: ProviderMetadata;
    createdAt:         string;
    updatedAt:         string;
}

export interface Formats {
    thumbnail: Large;
    small:     Large;
    large:     Large;
    medium:    Large;
}

export interface Large {
    name:              string;
    hash:              string;
    ext:               string;
    mime:              string;
    path:              null;
    width:             number;
    height:            number;
    size:              number;
    url:               string;
    provider_metadata: ProviderMetadata;
}

export interface ProviderMetadata {
    public_id:     string;
    resource_type: ResourceType;
}

export enum ResourceType {
    Image = "image",
}

export interface Stack {
    id:   number;
    name: string;
}

export interface Meta {
    pagination: Pagination;
}

export interface Pagination {
    page:      number;
    pageSize:  number;
    pageCount: number;
    total:     number;
}
